

easy_admin:
   site_name: 'API Practice in Symfony.'
   user:
      display_name: true
      display_avatar: false
   entities:
      BlogPost:
         class: App\Entity\BlogPost
         list:
            fields: ['id', { property: 'title', label: 'Heading' }, { property: 'published', label: 'Post Published' }, { property: 'slug', label: 'Post Slug' }]
      User:
        class: App\Entity\User

      Comment:
        class: App\Entity\Comment

   design:
      brand_color: '#1ABC9C'


